labels: []
body:
  - type: checkboxes
    id: first-check
    attributes:
      label: First check
      description: Please confirm and check all the following options.
      options:
        - label: "I have added a very descriptive title here."
          required: true
        - label: "I have used the GitHub search bar to find a similar subject and didn't find it."
          required: true
        - label: "I have already searched the [sandboxie-docs](https://github.com/sandboxie-plus/sandboxie-docs) repository (currently there are [synchronization issues](https://github.com/sandboxie-plus/Sandboxie/discussions/1756) with sandboxie-plus.com)."
          required: true
        - label: "I have already searched the other [support channels](https://github.com/sandboxie-plus/Sandboxie/discussions/1768#discussioncomment-2503401)."
          required: true
        - label: "I have already searched the [cached copy](https://github.com/Sandboxie-Website-Archive/sandboxie-website-archive.github.io) of the old Sandboxie forum: `site:https://sandboxie-website-archive.github.io/www.sandboxie.com/old-forums/`"
          required: true
        - label: "I have already searched the [contributing guidelines](https://github.com/sandboxie-plus/Sandboxie/blob/master/CONTRIBUTING.md)."
          required: true
        - label: "I understand that problem reports usually require a [new issue](https://github.com/sandboxie-plus/Sandboxie/issues/new/choose) with more details to be provided."
          required: true

  - type: textarea
    id: description
    attributes:
      label: Suggestion(s)
      description: |
        Share low priority ideas for new features (high priority requests require a [new issue](https://github.com/sandboxie-plus/Sandboxie/issues/new/choose)).
    validations:
      required: true
