name: Update copyright year(s) in license files

on:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 AM on January 1

  workflow_dispatch:

jobs:
  update-license-year-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          transform: (?<=Copyright 2020 - )(?<from>\d{4})?-?(\d{4})?
          path: |
            LICENSE.Plus
            Sandboxie/**/LICENSE.TXT
            Installer/license.txt
            *.h
            *.rc
            *.c
            *.cpp
            *.asm

  update-license-year-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          transform: (?<=Copyright (C) 2020-2023 )(?<from>\d{4})?-?(\d{4})?
          path: |
            Installer/Sandboxie-Plus.iss
