name: Update copyright year(s) in license files

on:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 AM on January 1

  workflow_dispatch:

jobs:
  update-license-year-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          transform: (?<=Copyright )(?<from>2020)? - ?(\d{4})?
          path: |
            LICENSE.Plus
            Sandboxie/**/LICENSE.TXT
            Installer/license.txt
            SandboxiePlus/SandMan/LICENSE
            Sandboxie/core/svc/ProcessServer.h
            Sandboxie/core/drv/my_fltkernel.h

  update-license-year-2:
    needs: update-license-year-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            Installer/Sandboxie-Plus.iss
            Sandboxie/core/drv/api_flags.h
            SandboxiePlus/QSbieAPI/SbieTrace.h
            Sandboxie/core/svc/msgids.h
            Sandboxie/**/**/*.cpp
            Sandboxie/**/**/*.asm
            Sandboxie/**/**/*.c
            SandboxiePlus/**/**/*.cpp
            SandboxiePlus/**/**/*.h
            SandboxieTools/**/*.cpp
            SandboxieTools/**/*.h

  update-license-year-3:
    needs: update-license-year-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          transform: (?<=Copyright )(?<from>2020)?)?
          path: |
            Sandboxie/apps/com/header.h
            Sandboxie/core/drv/hook.h
            Sandboxie/core/drv/log_buff.h
