name: Publish to WinGet
on:
  release:
    types: [released]
jobs:
  publish-plus:
    runs-on: windows-latest # action can only be run on Windows
    concurrency:
      group: plus-${{ github.event.release.tag_name }}  # Use the release tag name for concurrency
      cancel-in-progress: true  # Cancel any in-progress runs for the same group
    steps:
      - name: Publish Sandboxie-Plus
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Sandboxie.Plus
          installers-regex: "Sandboxie-Plus.*.exe$"
          token: ${{ secrets.WINGET_TOKEN }}

  publish-classic:
    runs-on: windows-latest
    concurrency:
      group: classic-${{ github.event.release.tag_name }}  # Use the release tag name for concurrency
      cancel-in-progress: true  # Cancel any in-progress runs for the same group
    steps:
      - name: Get Sandboxie-Classic version
        id: get_version
        run: |
          $VERSION="${{ github.event.release.name }}" -replace '^.*/ '
          "CLASSIC_VER=$VERSION" >> $env:GITHUB_OUTPUT
        shell: pwsh
      - name: Publish Sandboxie-Classic
        uses: vedantmgoyal9/winget-releaser@main
        with:
          version: ${{ steps.get_version.outputs.CLASSIC_VER }}
          identifier: Sandboxie.Classic
          installers-regex: "Sandboxie-Classic.*.exe$"
          token: ${{ secrets.WINGET_TOKEN }}
